# Server Port
port = 6379

# Data Directory and RDB Backup
dir = /data
dbfilename = dump.rdb

# Append-Only File (AOF) settings
appendonly = yes
appenddirname = appendonlydir
appendfilename = appendonly.aof
appendfsync = everysec

# Authentication (Uncomment to enable)
# requirepass = your_secret_password